// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Это описание эндпоинта",
                "tags": [
                    "пример23"
                ],
                "summary": "Тестовый эндпоинт",
                "responses": {
                    "200": {
                        "description": "Техническая информация",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/": {
            "get": {
                "description": "Получить мероприятия",
                "tags": [
                    "events"
                ],
                "responses": {
                    "200": {
                        "description": "event",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event_id}": {
            "get": {
                "description": "Получить мероприятие по ID",
                "tags": [
                    "events"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID мероприятия",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
